name: Docker image build and push
on: [push]
jobs:
  Docker-Build-Push: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: docker image build
        run: docker build -t apykwan/flask-redis:latest .
      - name: list docker image
        run: docker image ls
      - name: dockerhub log in
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: push to docker hub
        run: docker image push apkwan/flask-redis:latest